config/routes.rb
PleaseWork::Application.routes.draw do

  get "menu/menu"

  get "goodbye/bye"

  get "hello/hi"

  get "welcome/index"

   root :to => 'welcome#index'
   match '/hello' => 'hello#hi'
   match '/welcome' => 'welcome#index'
   match '/form' => 'welcome#form'
   match '/veg' => 'welcome#menu'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #layout 'main'
end

app/controllers/goodbye_controller.rb
class GoodbyeController < ApplicationController
  def bye
  		#render:template=>"hello/hi" 
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'hello'
  def hi
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def menu 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goodbye_helper.rb
module GoodbyeHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/goodbye/bye.html.erb
<h1>Goodbye :( !!!</h1>
<p>Find me in app/views/goodbye/bye.html.erb</p>

app/views/hello/hi.html.erb
<% content_for :title, "Resume"%>
<%content_for :col2 do %>
<h1>Hey how are ya :)!!!</h1>

<%= link_to "Welcome :)", welcome_path(@index) %>

<p>Find me in app/views/hello/hi.html.erb</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PleaseWork</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/hello.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PleaseWork</title>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
 	 <%= javascript_include_tag "application" %>
 	 <%= csrf_meta_tags %>
	</head>
	<body>
		<div>
			<div id ="col1">  </div>
			<div id ="col2"> <%= yield :col2 %> </div>
			<div id ="col3">  </div>
		</div>
	</body>
</html>

app/views/welcome/denied.html.erb
<p>
Access denied! </br>
Please recheck your username and password
</p>

app/views/welcome/form.html.erb
<h1>Fill out my form :) !!!</h1>

<%=form_tag do %>
</br>
<%=label_tag(:body, "Please enter your log in details:")%> </br></br>
	<%=label_tag(:body, "Username:")%> 
	<%=text_field_tag(:body)%> </br>
	<%=label_tag(:body, "Password:")%>
	<%=text_field_tag(:body)%> </br></br>
	<%=submit_tag("Submit")%> 

	<%end%>

app/views/welcome/granted.html.erb
<p>
Access granted! </br>
WELCOME :D
</p>

app/views/welcome/index.html.erb
<h1>Welcome :)!!!</h1>

<%= link_to "My Form :)", form_path(@form) %>
</br></br>
<%= link_to "My Other Form :L", veg_path(@menu) %>
</br></br>
<%= link_to "Hello!!", hello_path(@hi) %>

<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/menu.html.erb
</br></br>
<p><b>Menu :) </b></p></br>
<p>Are you a Vegetarian? </p>

<p><%=radio_button_tag(:veg,"Vegetarian")%> YES</p>
<p><%=radio_button_tag(:nonveg,"Non-Vegetarian")%> NO</p>
</br>
<p>What are your favourite sports? (Please choose more than 1) </p>
<p><%=check_box_tag(:sport)%> Soccer</p>
<p><%=check_box_tag(:sport)%> Hurling</p>
<p><%=check_box_tag(:sport)%> Rugby</p>
<p><%=check_box_tag(:sport)%> Gaelic Football</p>
<p><%=check_box_tag(:sport)%> Cricket</p>
</br>
<%=submit_tag("Submit")%> 